name: Continuous Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c칩digo fuente
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Obtener la versi칩n m치s alta desde Docker Hub
      - name: Determine Next Version on DockerHub
        id: get_version
        run: |
          REPO=${{ secrets.DOCKER_USERNAME }}/holamundoc

          # Obtener tags y extraer versiones
          tags=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags/" | jq -r '.results[].name' | grep -oP '^v\d+\.\d+' | sort -V)

          # Determinar la nueva versi칩n
          if [ -z "$tags" ]; then
            NEW_VERSION="v1.0"
          else
            highest_version=$(echo "$tags" | tail -n 1)
            NEW_VERSION=$(echo "$highest_version" | awk -F. '{print "v" $1 "." $2+1}')
          fi

          echo "next=$NEW_VERSION" >> $GITHUB_OUTPUT

      # 3. Log in a DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y subir la imagen Docker a DockerHub
      - name: Build and Publish Docker Image
        run: |
          REPO=${{ secrets.DOCKER_USERNAME }}/holamundoc
          NEW_VERSION=${{ steps.get_version.outputs.next }}

          docker build . --file Dockerfile \
            --tag $REPO:$NEW_VERSION \
            --tag $REPO:latest
          docker push $REPO:$NEW_VERSION
          docker push $REPO:latest

  deploy:
    name: Deploy Docker Image on EC2
    runs-on: self-hosted 
    needs: build-and-publish

    steps:
      - name: Install Docker on EC2 (Amazon Linux 2023)
        run: |
          # Actualizar el sistema
          sudo yum update -y
          
          # Instalar dependencias para Docker
          sudo yum install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          # Agregar el repositorio oficial de Docker
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          
          # Instalar Docker
          sudo yum install -y docker-ce docker-ce-cli containerd.io
          # Iniciar y habilitar Docker
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run Docker container
        run: |
          docker run -d --name holamundoc -p 80:8080 millanda29/holamundoc:${{ env.new_version }}
